apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: busybox
spec:
  replicas: 1
  minReadySeconds: 30
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
        - name: busybox
          image: busybox
          command: ["sh", "-c", "cd /conf && chmod +x *.sh && copy-init-files.sh"]
          volumeMounts:
            - name: oracle-db-ords-config
              mountPath: "/conf"
            - name: oracle-db-ords-config-persistent
              mountPath: "/opt/oracle/ords/config/ords"

      volumes:
        - name: oracle-db-ords-config
          configMap:
            name: oracle-db-ords-config
        - name: oracle-db-ords-config-persistent
          persistentVolumeClaim:
            claimName: oracle-db-ords
