
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: oracle-db-enterprise
spec:
  replicas: 1
  minReadySeconds: 30
  selector:
    matchLabels:
      app: oracle-db-enterprise
  template:
    metadata:
      labels:
        app: oracle-db-enterprise
    spec:
      hostname: oracle-db-enterprise
      containers:      
      - name: oracle-db-enterprise
        image: fra.ocir.io/oraseemeadesandbox/pdos/oracle/database:19.3.0-ee
        env:
        - name: ORACLE_SID
          value: "ORCLCDB"
        - name: ORACLE_PDB
          value: "ORCLPDB1"
        - name: ORACLE_PWD
          value: "PDos00###"
        volumeMounts:
        - name: oracle-db-config
          mountPath: /opt/oracle/scripts/setup
        - name: oracle-db-data
          mountPath: /opt/oracle/oradata
        ports:
        - containerPort: 1521
        livenessProbe:
          tcpSocket:
            port: 1521
          initialDelaySeconds: 300
          periodSeconds: 30
      imagePullSecrets:
        - name: registry-secret
      volumes:
        - name: oracle-db-config
          configMap:
            name: oracle-db-config
        - name: oracle-db-data
          persistentVolumeClaim:
            claimName: oracle-db-data
      initContainers:
        - name: chown-oradata
          command: ["sh", "-c", "chown -R 54321:54321 /opt/oracle/oradata"]
          image: busybox
          volumeMounts:
            - name: oracle-db-data
              mountPath: /opt/oracle/oradata

---
apiVersion: v1
kind: Service
metadata:
  name: oracle-db-enterprise-1
spec:
  ports:
  - port: 1521
    targetPort: 1521
    protocol: TCP
  selector:
    app: oracle-db-enterprise
